# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-merge-conflict
    -   id: check-case-conflict
-   repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.0
    hooks:
    -   id: gdformat

exclude: ^addons/
